### ISSUE TITLE
download_lm_en.sh broken

### ISSUE THREAD

**Issue by haoqiang** [PaddlePaddle/DeepSpeech#268] opened 2018-08-06 13:59 UTC
Hi all,

Got error when trying run `/models/lm/download_lm_en.sh` to download http://paddlepaddle.bj.bcebos.com/model_zoo/speech/common_crawl_00.prune01111.trie.klm

```
{
"code": "AccountOverdue",
"message": "Your request is denied because there is an overdue bill of your account.",
"requestId": "4b684141-1175-4691-a9cd-52c458a94845"
}
```

**Comment by olegakbarov** [comment] 2018-08-07 15:15
Same here. Please fix ASAP.

**Comment by nsmetanin** [comment] 2018-08-14 10:07
Is it possible to train this model according to https://github.com/PaddlePaddle/DeepSpeech#english-lm ? There's some lack of dataset preparation code for LM

**Comment by derekpankaew** [comment] 2018-09-27 07:10
Unable to download as well. Is anyone aware of any other mirror or links?

**Comment by ashwan1** [comment] 2018-10-10 12:46
I am unable to download as well. run_infer.sh gives following error:
![image](https://user-images.githubusercontent.com/25479695/46737189-84458f00-ccb8-11e8-922e-2981d78f0d43.png)
and http://paddlepaddle.bj.bcebos.com/model_zoo/speech/common_crawl_00.prune01111.trie.klm gives following error: 
{"code":"NoSuchBucket","message":"The specified bucket does not exist.","requestId":"1b9b1591-16c6-414c-8939-daffa2dd1686"}

**Comment by tarashakhurana** [comment] 2018-10-16 09:34
Does anyone have a fix for this?

**Comment by dileep1996** [comment] 2018-10-17 04:43
I emailed Xinghai regarding the same. Yibing is looking into this now. Will update here if I get any further response

**Comment by qianghuang84** [comment] 2018-11-09 09:12
依然还是无法下载

**Comment by 1973Blunt** [comment] 2018-11-12 12:59
still unable to download

**Comment by 1973Blunt** [comment] 2018-11-12 13:18
https://github.com/PaddlePaddle/DeepSpeech/issues/288#issue-370877503

**Comment by sahilanguralla** [comment] 2018-11-28 15:40
+1. Please fix this ASAP.

**Comment by Ywz2018** [comment] 2018-12-02 02:35
I encountered this problem too.

**Comment by seethagithub** [comment] 2018-12-15 00:35
I have the same issue

**Comment by mehercharan** [comment] 2018-12-18 05:49
Any update on this? please provide us with a location to download the LM

**Comment by NeerajGulia** [comment] 2018-12-25 06:10
{"code":"NoSuchBucket","message":"The specified bucket does not exist.","requestId":"babf239d-362c-4f62-90b8-fb290d271f83"}

Is there a way to download the model?

**Comment by wudeshi** [comment] 2018-12-31 06:15
what?,

**Comment by bkmgit** [comment] 2019-01-08 15:47
This is the Chinese data set.

**Comment by ces-bertino** [comment] 2019-01-08 18:07
What I tried to say is that you need to use the URL line from the Chinese download script in the english model download script. Hence, the new english model script would be like below:

#! /usr/bin/env bash

. ../../utils/utility.sh

URL=http://cloud.dlnel.org/filepub/?uuid=5cd1688e-78d9-4b9e-9c2f-6f104bd5b518
MD5="099a601759d467cd0a8523ff939819c5"
TARGET=./common_crawl_00.prune01111.trie.klm


echo "Download language model ..."
download $URL $MD5 $TARGET
if [ $? -ne 0 ]; then
    echo "Fail to download the language model!"
    exit 1
fi


exit 0

**Comment by NeerajGulia** [comment] 2019-01-09 10:39
> What I tried to say is that you need to use the URL line from the Chinese download script in the english model download script. Hence, the new english model script would be like below:
> 
> #! /usr/bin/env bash
> 
...
> exit 0

It will download the Chinese model and not the English model as you think.

**Comment by ces-bertino** [comment] 2019-01-09 19:35
> > What I tried to say is that you need to use the URL line from the Chinese download script in the english model download script. Hence, the new english model script would be like below:
> 
> It will download the Chinese model and not the English model as you think.

You're right. I incorrectly assumed the URL was pointing to the bucket and the target was the file.
Thanks.

**Comment by kuhanw** [comment] 2019-02-21 20:52
Hello,

Has there been any progress on this? I can confirm as of today the download link for download_lm_en.sh is still broken.

Cheers,

Kuhan

**Comment by lagon** [comment] 2019-02-26 11:22
The URL is still broken. Any update appreciated. 
Sincerely,
Miroslav

**Comment by mtbadakhshan** [comment] 2019-03-06 06:41
Is there any alternative English LM to use?
Thanks,
Taghi

**Comment by diegocardozo97** [comment] 2019-03-10 18:21
An alternative for the LM in english is in the Mozilla DeepSpeech implementation in github ([https://github.com/mozilla/DeepSpeech](https://github.com/mozilla/DeepSpeech))
In the releases the .tar with the models (example: "deepspeech-0.4.1-models.tar.gz") includes a file called lm.binary.
For me it worked when using it for the language model.

**Comment by rhamnett** [comment] 2019-03-25 14:56
Still broken

**Comment by aaronlyt** [comment] 2019-03-26 05:46
still broken

**Comment by rhamnett** [comment] 2019-04-08 09:33
> An alternative for the LM in english is in the Mozilla DeepSpeech implementation in github (https://github.com/mozilla/DeepSpeech)
> In the releases the .tar with the models (example: "deepspeech-0.4.1-models.tar.gz") includes a file called lm.binary.
> For me it worked when using it for the language model.

This definitely works but would be good to fix the original issue

**Comment by code-R** [comment] 2019-04-09 07:19
@ces-bertino do you have the mandarin trained model? the link seems to be broken to test.. if you have can you please let me know? I would like to host the models in s3 for others.

**Comment by ces-bertino** [comment] 2019-04-11 03:55
> @ces-bertino do you have the mandarin trained model? the link seems to be broken to test.. if you have can you please let me know? I would like to host the models in s3 for others.

Sorry, but I didn't keep the mandarin trained model.

**Comment by haowang5128** [comment] 2019-05-06 06:53
https://deepspeech.bj.bcebos.com/en_lm/common_crawl_00.prune01111.trie.klm WORKING
http://paddlepaddle.bj.bcebos.com/model_zoo/speech/common_crawl_00.prune01111.trie.klm NOT WORKING

**Comment by Shashank112** [comment] 2019-07-25 20:42
I am still not able to download English model. It stops after 2 GB. Please help me with working link. Thank you.

**Closed** 2021-05-12 05:14 UTC
